"on":
  push:
    branches:
      - main
name: Deploy to backend
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Debug build env (set/unset)
        run: |
          echo "PORTER_NPM_TOKEN: ${{ secrets.PORTER_NPM_TOKEN }}"
          echo "PORTER_NPM_TASKFORCESH_TOKEN: ${{ secrets.PORTER_NPM_TASKFORCESH_TOKEN }}"
          echo "PORTER_TURBO_TOKEN: ${{ secrets.PORTER_TURBO_TOKEN }}"
          echo "PORTER_TURBO_TEAM: ${{ vars.PORTER_TURBO_TEAM }}"
          echo "TURBO_TEAM: ${{ vars.TURBO_TEAM }}"
        env:
          PORTER_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PORTER_NPM_TASKFORCESH_TOKEN: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
          PORTER_TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          PORTER_TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      - name: Deploy stack
        timeout-minutes: 30
        run: |
          porter apply \
            --secrets "PORTER_NPM_TOKEN=$PORTER_NPM_TOKEN,PORTER_NPM_TASKFORCESH_TOKEN=$PORTER_NPM_TASKFORCESH_TOKEN,PORTER_TURBO_TOKEN=$PORTER_TURBO_TOKEN,PORTER_TURBO_TEAM=$PORTER_TURBO_TEAM"
        env:
          PORTER_APP_NAME: backend
          PORTER_CLUSTER: "1"
          PORTER_DEPLOYMENT_TARGET_ID: 33c402f7-047b-4765-8233-bf9494942ea4
          PORTER_HOST: https://noe-dev.withporter.run
          PORTER_PROJECT: "1"
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1104217266 }}
          PORTER_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PORTER_NPM_TASKFORCESH_TOKEN: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
          PORTER_TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          PORTER_TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          DOCKER_BUILDKIT: "1"
