"on":
  pull_request:
    paths:
      - "**"
      - "!.github/workflows/porter_**"
name: Deploy to Preview Environment
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Debug build env (set/unset)
        run: |
          echo "PORTER_NPM_TOKEN: $([[ -n \"$PORTER_NPM_TOKEN\" ]] && echo set || echo unset)"
          echo "PORTER_NPM_TASKFORCESH_TOKEN: $([[ -n \"$PORTER_NPM_TASKFORCESH_TOKEN\" ]] && echo set || echo unset)"
          echo "PORTER_TURBO_TOKEN: $([[ -n \"$PORTER_TURBO_TOKEN\" ]] && echo set || echo unset)"
          echo "PORTER_TURBO_TEAM: $([[ -n \"$PORTER_TURBO_TEAM\" ]] && echo set || echo unset)"
          echo "TURBO_TEAM: $([[ -n \"$TURBO_TEAM\" ]] && echo set || echo unset)"
        env:
          PORTER_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PORTER_NPM_TASKFORCESH_TOKEN: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
          PORTER_TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          PORTER_TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      - name: Build and deploy preview environment
        timeout-minutes: 30
        run: |
          exec porter apply -f ./porter.yaml --preview \
            --secrets "PORTER_NPM_TOKEN=$PORTER_NPM_TOKEN,PORTER_NPM_TASKFORCESH_TOKEN=$PORTER_NPM_TASKFORCESH_TOKEN,PORTER_TURBO_TOKEN=$PORTER_TURBO_TOKEN,PORTER_TURBO_TEAM=$PORTER_TURBO_TEAM"
        env:
          PORTER_APP_NAME: backend
          PORTER_CLUSTER: "1"
          PORTER_HOST: https://noe-dev.withporter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "1"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
          PORTER_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PORTER_NPM_TASKFORCESH_TOKEN: ${{ secrets.NPM_TASKFORCESH_TOKEN }}
          PORTER_TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          PORTER_TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          DOCKER_BUILDKIT: "1"
